version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
  nginx:
    depends_on:
        - api
        - client
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - "80:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    ports: 
      - "8080:8080"