version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    expose: 3000
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - "80:80"