version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - "80:80"